MERGED_MODELS = {
    "calit2": ("LSTMAD", "RobustPCA"),
    "cicids": ("MCD", "RobustPCA"),
    "creditcard": ("PCA", "MCD", "LSTMAD", "CNN", "USAD"),
    "Daphnet": ("AutoEncoder", "OmniAnoomaly", "KMeansAD", "KNN"),
    "Exathlon": ("PCA", "AutoEncoder", "ALLM4TS", "EIF", "CNN"),
    "Gecco": ("PCA", "OAF", "USAD"),
    "Genesis": ("KmeansAD", "OAF", "LSTMAD"),
    "Ghl": ("OmniAnomaly", "USAD"),
    "GutenTAG": ("OmniAnomaly", "PCA", "OAF"),
    "metro": ("CBLOF", "TranAD", "EIF", "HBOS", "MCD"),
    "MITDB": ("CNN", "DONUT", "ALLM4TS", "IFOREST"),
    "MSL": ("KMeansAD", "CNN", "IFOREST", "OnmiAnomaly", "PCA"),
    "OPPORTUNITY": ("PCA", "IFOREST", "MCD", "CBLOF"),
    "PSM": ("AutoEncoder", "MCD", "CNN", "DONUT"),
    "ROOM-OCCU": ("MCD", "OCSVM", "COPOD"),
    "SMAP": ("KmeanAD", "CNN", "IFOREST"),
    "SMD": ("PCA", "KMeansAD", "OmniAnomaly", "CNN"),
    "SVDB": ("OmniAnomaly", "USAD", "PCA", "IFOREST"),
    "SWAN": ("RobustPCA", "MCD"),
}
